# Each new term in the Fibonacci sequence is generated by adding the previous two terms.
# By starting with 1 and 2, the first 10 terms will be:

# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

# By considering the terms in the Fibonacci sequence whose values do not exceed four million,
# find the sum of the even - valued terms.

def main():
    MAX = 4000000
    current = 2
    previous = 1
    sum = 0

    while current < MAX:
        if current % 2 == 0:
            sum += current

        temp = current
        current += previous
        previous = temp

        print(sum)


if __name__ == "__main__":
    main()
